config/routes.rb
UserCenterClient::Application.routes.draw do
  get "/privacy" => "home#privacy", :as => :privacy

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    session[:cas_user]
  end
  helper_method :current_user
  
  def site_name
    case
    when request.host =~ /myasics/
      "My ASICS SSO Demo"
    when request.host =~ /asics/
      "ASICS SSO Demo"
    when request.host =~ /isafeplayer/
      "Different Domain SSO Demo"
    else
      "Demo"
    end
  end
  helper_method :site_name
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter CASClient::Frameworks::Rails::Filter, :only => [:privacy]

  def index
  end

  def privacy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="wrapper">
  <header id="header">
    <h1><a href="/" id="logo"><%= site_name %></a></h1>
  </header>
  <section id="main">
    <h2>Welcome to <%= site_name %></h2>
    <article class="form_login">
      <h2><%= link_to "Private Page", privacy_path %></h2>
      <% unless current_user %>
        <%= render_ajax_login_form %>
      <% end %>
    </article>
  </section>
</div>

app/views/home/privacy.html.erb
<div id="wrapper">
  <header id="header">
    <h1><a href="/" id="logo"><%= site_name %></a></h1>
  </header>
  <section id="main">
    <h2>This is private page.</h2>
    <article class="form_login">
      <h2><%= link_to "Home Page", root_path %></h2>
    </article>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ASICS</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script src="http://www.asics.co.uk/feeds/clean_header_footer.js" type="text/javascript"></script>
</head>
<body>
<!-- <div id="holder"> -->
  <div id="top">
    <div id="top_container" class="clearfix">
      <% if current_user %>
        <ul id="navigation">
          <li><a href="/" ><%= current_user %></a></li>
          <li class="vr_top"></li>
          <li><%= link_to("Logout", logout_path) %></li>
        </ul>
      <% else %>
        <ul id="navigation">
          <li><%= link_to("Register", "#{CASClient::Frameworks::Rails::Filter.config[:cas_base_url]}user/new?service=#{request.url}") %></li>
          <li class="vr_top"></li>
          <li><%= link_to("Login", "#{CASClient::Frameworks::Rails::Filter.config[:login_url]}?service=#{request.url}") %></li>
        </ul>
      <% end %>
    </div>
  </div>

  <%= yield %>

<!-- </div> -->
<script type="text/javascript">
  if (typeof minisite !== "undefined") minisite.write('footer');
</script>
</body>
</html>